### ISSUE TITLE
Object detection transfer supervised baseline replication issues

### ISSUE THREAD

**Issue by cowittig** [linusericsson/ssl-transfer#1]
Hi,

I am having troubles reproducing your supervised baseline for object detection with frozen backbone as a baseline for my own experiments. 

I am running detectron2 with ResNet50 torchvision weights converted to detectron2 with the official script and freeze the backbone. I have also tested the MSRA weights normally used by detectron2.

Results:
```
AP AP50 AP75
44.25 77.14 44.07 (mine, torchvision weights)
46.90 78.27 49.19 (mine, MSRA weights)
51.99 81.53 56.21 (yours, table 3 frozen backbone)
```

Could you share
- your detectron2 configuration files for your frozen and fine-tune experiments?
- how you are freezing the backbone? Are you using the detectron2 FREEZE_AT config parameter?

I am running the detectron2 VOC configuration modified with the settings in section 4.3 from your paper and freeze the backbone using FREEZE_AT:
```
_BASE_: "censored-path/detectron2/configs/PascalVOC-Detection/faster_rcnn_R_50_FPN.yaml"
MODEL:
  BACKBONE:
    FREEZE_AT: 5    # freeze all resnet stages
  WEIGHTS: "censored-path/models/r50-imagenet1k-torchvision.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
INPUT:
  FORMAT: "RGB"
SOLVER:
  STEPS: (96000, 128000)
  MAX_ITER: 144000
  WARMUP_ITERS: 100
  BASE_LR: 0.0025
  IMS_PER_BATCH: 2
  CHECKPOINT_PERIOD: 24000
OUTPUT_DIR: censored-path
```

Best,
Constantin
